import { createSlice } from "@reduxjs/toolkit";

const companies = [
  {
    NameOfCompany: "OLA Cabs\n(ANI Technologies)",
    ProfileOffered: "Data Scientist",
    Location: "Bangaluru",
    FunctionalArea: "B.Tech CSE",
    AnnualCTC: "INR. 9.50 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Online written test (Aptitude)",
    Round2: "Group Discussion",
    Round3: "Technical Interview",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "A. P. Moller - Maersk Line India",
    ProfileOffered: "Software Intern",
    Location: "Mumbai",
    FunctionalArea: "B.Tech CSE, ECE",
    AnnualCTC: "INR. 9.00 LPA",
    ForBatch: 2023,
    Round1: "Technical written (Aptitude + Technical + Coding)",
    Round2: "Technical Interview",
    Round3: "Technical + Managerial Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Lowe's India",
    ProfileOffered: "Associate Software Engineer",
    Location: "Bangalore",
    FunctionalArea: "B.Tech CSE, ECE",
    AnnualCTC: "INR. 19.34 LPA",
    ForBatch: 2023,
    Round1: "Online assessment and Coding Interview",
    Round2: "Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Hevo Data",
    ProfileOffered: "Technical Writer - Intern",
    Location: "Bangalore",
    FunctionalArea: "B.Tech CSE, ECE",
    AnnualCTC: "INR. 8.00 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Written Exam",
    Round2: "Group Discussion OR 2nd Technical Test",
    Round3: "Technical + HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Tek Systems Global Services Pvt Ltd.",
    ProfileOffered: "Trainee Engineer",
    Location: "Bangalore / Hyderabad",
    FunctionalArea: "B.Tech CSE",
    AnnualCTC: "INR. 6.00 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Aptitude Test ",
    Round2: "Group Discussion",
    Round3: "Technical Interview (Multiple rounds)",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "Mphasis",
    ProfileOffered: "Associate Software Engineer",
    Location: "Bangalore, Chennai, Pune, Mumbai, Hyderabad, and Noida",
    FunctionalArea: "B.Tech / M.Tech CSE, ECE",
    AnnualCTC: "INR. 4.00 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Online Test (Aptitude+Technical)",
    Round2: "Group Discussion",
    Round3: "Technical Interview",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "MAQ Software Pvt. Ltd.",
    ProfileOffered: "Associate Software Engineer",
    Location: "Bangalore",
    FunctionalArea: "B.Tech CSE",
    AnnualCTC: "INR. 7.00 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Aptitude Test ",
    Round2: "Technical (Coding round)",
    Round3: "Technical Interview",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "CodeNation Innovation Labs",
    ProfileOffered: "Software Development Engineer",
    Location: "Bangalore",
    FunctionalArea: "B.Tech / M.Tech CSE",
    AnnualCTC: "INR. 29.50 LPA",
    ForBatch: 2023,
    Round1: "Coding Round",
    Round2: "Technical Interview               (2 - 3 Rounds)",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Acodemy.in",
    ProfileOffered: "Business Development Executive",
    Location: "Pan India",
    FunctionalArea: "MBA, B.Tech All, BCA",
    AnnualCTC: "INR. 5.00 LPA",
    ForBatch: "2022 & 2023",
    Round1: '""',
    Round2: '""',
    Round3: '""',
    Round4: '""',
  },
  {
    NameOfCompany: "Inncircle Technology Pvt. Ltd.",
    ProfileOffered: "Full Stack Developer",
    Location: "Hyderabad",
    FunctionalArea: "B.Tech CSE",
    AnnualCTC: "INR. 8.00 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Written/Aptitude test",
    Round2: "Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Mantra Labs",
    ProfileOffered: "Trainee Software Engineer",
    Location: "Bangalore",
    FunctionalArea: "B.Tech / M.Tech CSE",
    AnnualCTC: "INR. 4.00 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Aptitude (Technical & General)  ",
    Round2: "Programming Test",
    Round3: "Technical Interview",
    Round4: " Interview Aptitude  ",
  },
  {
    NameOfCompany: "DXC Technologies",
    ProfileOffered: "Associate Professional",
    Location: "Noida",
    FunctionalArea: "B.Tech CSE, ECE",
    AnnualCTC: "INR. 4.00 LPA",
    ForBatch: "2022 & 2023 & 2024",
    Round1: "Written Test (Aptitude + English + Technical)",
    Round2: "Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Alif Semiconductor India Pvt. Ltd.",
    ProfileOffered: "Graduate Engineer Trainee",
    Location: "Bangalore",
    FunctionalArea: "B.Tech CSE, ECE",
    AnnualCTC: "INR. 4.50 LPA",
    ForBatch: "2022 & 2023",
    Round1: '""',
    Round2: '""',
    Round3: '""',
    Round4: '""',
  },
  {
    NameOfCompany: "Learning Routes Pvt. Ltd.",
    ProfileOffered: "Sales Associate",
    Location: "Pan India",
    FunctionalArea: "B.Tech All, BCA, MBA, ASCO",
    AnnualCTC: "INR. 5.34 LPA ",
    ForBatch: 0,
    Round1: "Group Discussion ",
    Round2: " Extempore",
    Round3: "HR Interview",
  },
  {
    NameOfCompany: "QA Infotech Pvt. Ltd.",
    ProfileOffered:
      "Software Test Automation / Performance Testing / DevOps / Software Development",
    Location: "Noida",
    FunctionalArea: "B.Tech / M.Tech - CSE ",
    AnnualCTC: "INR. 3.00 LPA to INR. 12.00 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Technical MCQ Round",
    Round2: "Coding Round",
    Round3: "Technical Interview",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "SAP Labs",
    ProfileOffered: "Scholar @ SAP",
    Location: "Bangalore",
    FunctionalArea: "B.Tech CSE, ECE",
    AnnualCTC: "INR. 8.25 LPA",
    ForBatch: "2022 & 2023 & 2024",
    Round1: " Online Test (Coding section & MCQs)",
    Round2: "2 Rounds of Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Hanu Software",
    ProfileOffered: "Cloud Engineer - PAAS / IAAS",
    Location: "Noida",
    FunctionalArea: "B.Tech CSE",
    AnnualCTC: "INR. 6.00 LPA",
    ForBatch: "2022 & 2023",
    Round1: " \nOnline Assessment",
    Round2: "Group Discussion ",
    Round3: "Personal Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Brillio Technology",
    ProfileOffered: "Software Engineer",
    Location: "Bangalore / Pune",
    FunctionalArea: "B.Tech CSE, IT",
    AnnualCTC: "INR. 4.50 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Technical Aptitude and coding round.",
    Round2: "Technical coding round on online platform OR Group discussion",
    Round3: "Technical Interview",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "BETSOL",
    ProfileOffered: "Associate Software Engineer ",
    Location: "Bangalore",
    FunctionalArea: "B.Tech/M.Tech CSE/IT/ECE",
    AnnualCTC: "INR. 4.00 LPA - INR. 6.00 LPA",
    ForBatch: 2023,
    Round1: "Online test (Aptitude+Technical)",
    Round2: "Group Discussion ",
    Round3: "Technical Interview (1 pr 2 rounds)",
    Round4: "Managerial + HR Interview",
  },
  {
    NameOfCompany: "Yellow Class",
    ProfileOffered: "SDE - Mobile Flutter",
    Location: "Gurgaon",
    FunctionalArea: "B.Tech CSE",
    AnnualCTC: "INR. 15.00 LPA",
    ForBatch: 2023,
    Round1: "Coding Round",
    Round2: "Techical interview",
    Round3: "Technical + Managerial Interview",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "Jellyfish Technology",
    ProfileOffered: "Software Trainee / QA Trainee",
    Location: "Noida",
    FunctionalArea: "B.Tech CSE, ECE",
    AnnualCTC: "INR. 3.60 LPA",
    ForBatch: "2022 & 2023",
    Round1: "HR Round",
    Round2: "Coding Test",
    Round3: "Technical Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Coforge Technologies",
    ProfileOffered: "Associate",
    Location: "Noida",
    FunctionalArea: "B.Tech CSE, ECE",
    AnnualCTC: "INR. 3.65 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Online Test ",
    Round2: "Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Evosys Global Pvt. Ltd.",
    ProfileOffered: "Oracle Consultant / Technical Consultant",
    Location: "Ahmedabad / Pune  ",
    FunctionalArea: "B.Tech / M.Tech CSE, ECE, Biotech, B.Pharma, MBA",
    AnnualCTC: "UG : INR. 3.60 LPA\nPG : INR. 4.20 LPA",
    ForBatch: 2023,
    Round1: "Aptitude Test ",
    Round2: "Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Hashedin by Deloitte",
    ProfileOffered: "Software Engineer",
    Location: "Bangalore",
    FunctionalArea: "B.Tech CSE",
    AnnualCTC: "INR. 8.00 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Online Test (Aptitude+Technical)",
    Round2: "Technical (2 rounds)",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Glassbeam Software",
    ProfileOffered: "Solution Engineer",
    Location: "Bangalore",
    FunctionalArea: "B.Tech CSE",
    AnnualCTC: "INR. 4.20 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Aptitude Test ",
    Round2: "Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Paytm",
    ProfileOffered:
      "Back Development Engineer / DevOps Engineer / QA Engineer / Tech Ops Engineer",
    Location: "Bangalore",
    FunctionalArea: "B.Tech / M.Tech - CSE, IT",
    AnnualCTC: "INR. 5.00 LPA - INR. 7.00 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Coding Test",
    Round2: "Technical Round-1",
    Round3: "Technical Round-2",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "Tata Class Edge",
    ProfileOffered: "Consultant",
    Location: "Pan India",
    FunctionalArea: "B.Tech CSE, IT",
    AnnualCTC: "INR. 12.00 LPA",
    ForBatch: 2023,
    Round1: "Online Test (Aptitude+Technical)",
    Round2: "Group Discussion",
    Round3: "Technical Interview",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "Merkle Sokrati ",
    ProfileOffered: "Business Analyst",
    Location: "Pune",
    FunctionalArea: "B.Tech / M.Tech All",
    AnnualCTC: "INR. 6.20 LPA",
    ForBatch: 2023,
    Round1: "Online Test – Verbal, Analytical, Logical",
    Round2: "Technical interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Hevo Data",
    ProfileOffered: "Technical Writer",
    Location: "Bangalore",
    FunctionalArea: "B.Tech CSE",
    AnnualCTC: "INR. 8.00 LPA",
    ForBatch: 2023,
    Round1: "Online Test (Aptitude+Technical)",
    Round2: "Group Discussion",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Appcino - A Xebia Company",
    ProfileOffered: "Trainee Software Engineer",
    Location: "Jaipur / Bangalore / Gurugram",
    FunctionalArea: "B.Tech / M.Tech - CSE, IT",
    AnnualCTC: "INR. 3.50 LPA",
    ForBatch: 2023,
    Round1: "Technical Aptitude Test",
    Round2: "Technical interview ",
    Round3: "Interview Management",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "Mitsogo Technologies",
    ProfileOffered: "Software Analyst ",
    Location: "Pune / Bangalore",
    FunctionalArea: "B.Tech/M.Tech -  CSE, IT, ECE ",
    AnnualCTC: "INR. 6.25 LPA - INR. 9.23 LPA",
    ForBatch: 2023,
    Round1: "Online Test ",
    Round2: "Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Ajirasoft",
    ProfileOffered: "Full Stack Developer",
    Location: "Chennai",
    FunctionalArea: "B.Tech / M.Tech CSE, IT",
    AnnualCTC: "INR. 10.00 LPA",
    ForBatch: 0,
    Round1: "Technical Interview (Multiple Rounds)",
    Round2: "HR Interview",
    Round3: '""',
    Round4: '""',
  },
  {
    NameOfCompany: "Cyntexa",
    ProfileOffered: "Associate Software Developer",
    Location: "Jaipur",
    FunctionalArea: "B.Tech / M.Tech CSE",
    AnnualCTC: "INR. 4.03 LPA",
    ForBatch: 2023,
    Round1: "Coding Round (3 rounds Basic, medium and high level)",
    Round2: "HR Interview",
    Round3: '""',
    Round4: '""',
  },
  {
    NameOfCompany: "Capgemini",
    ProfileOffered: "Analyst",
    Location: "Pan India",
    FunctionalArea: "B.Tech CSE, ECE",
    AnnualCTC: "INR. 3.80 LPA",
    ForBatch: "2022 & 2023",
    Round1: "English and Technical MCQ - Cognitive Assessment",
    Round2: "Spoken English Assessment",
    Round3: "Coding Assessment",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "Planet Spark",
    ProfileOffered: "Business Development Counsellor",
    Location: "Pan India",
    FunctionalArea: "B.Tech All, MBA, BBA, B.Com",
    AnnualCTC: "INR. 6.50 LPA - INR. 7.60 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Group Discussion ",
    Round2: "Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Cognizant Technology",
    ProfileOffered: "GenC Elevate",
    Location: "Pan India",
    FunctionalArea: "B.Tech All",
    AnnualCTC: "INR. 5.00 LPA ",
    ForBatch: "2022 & 2023",
    Round1: "Aptitude Test",
    Round2: "Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    ProfileOffered: "GenC Next",
    AnnualCTC: "INR. 7.50 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Aptitude Test",
    Round2: "Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    ProfileOffered: "GenC ",
    AnnualCTC: "INR. 4.50 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Aptitude Test",
    Round2: "Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "MP2 IT",
    ProfileOffered: "Technical Associate ",
    Location: "Mathura",
    FunctionalArea: "M.Tech CSE",
    AnnualCTC: "INR. 2.40 LPA",
    ForBatch: "2022 & 2023",
    Round1: '""',
    Round2: '""',
    Round3: '""',
    Round4: '""',
  },
  {
    NameOfCompany: "Intellipaat",
    ProfileOffered: "Inside Sales Manager",
    Location: "Bangalore",
    FunctionalArea: "MBA, B.Tech All, BCA, BBA",
    AnnualCTC: "INR. 5.30 LPA",
    ForBatch: "2022 & 2023 & 2024",
    Round1: "Group Discussion ",
    Round2: "Technical Interview ",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Expert Lancing",
    ProfileOffered: "Research Analyst",
    Location: "Gurgaon",
    FunctionalArea: "B.Tech Biotech, ECE, B.Pharma",
    AnnualCTC: "INR. 3.00 LPA - INR. 4.50 LPA",
    ForBatch: 2023,
    Round1: "Coding Test Round-1",
    Round2: "Coding Test Round-2",
    Round3: "HR Interview",
  },
  {
    NameOfCompany: "Coditas Solutions LLP",
    ProfileOffered: "Associate Software Engineer",
    Location: "Pune",
    FunctionalArea: "B.Tech CSE, IT, ECE",
    AnnualCTC: "INR. 3.60 LPA - INR. 5.00 LPA",
    ForBatch: 2023,
    Round1: "Online Test (Aptitude + Technical + Eng)",
    Round2: "Group Discussion",
    Round3: "Technical Interview",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "Green Way Health",
    ProfileOffered: "Associate Software Engineer",
    Location: "Bangalore",
    FunctionalArea: "B.Tech CSE, ECE",
    AnnualCTC: "INR. 6.00 LPA",
    ForBatch: 2023,
    Round1: "Aptitude Test",
    Round2: "Technical Interview",
    Round3: "HR Interview",
  },
  {
    NameOfCompany: "Delta X",
    ProfileOffered: "Software Developer",
    Location: "Pan India",
    FunctionalArea: "B.Tech CSE, ECE",
    AnnualCTC: "INR. 6.00 LPA",
    ForBatch: 2023,
    Round1: "Aptitude Test",
    Round2: "Coding Test",
    Round3: "Technical Interview (1-2 Round)",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "Vassar Labs IT Solutions Private Limited",
    ProfileOffered: "Software Engineer",
    Location: "Hyderabad",
    FunctionalArea: "B.Tech CSE, ECE",
    AnnualCTC: "INR. 5.00 LPA",
    ForBatch: 2023,
    Round1: "Coding Test",
    Round2: "Technical Interview (1-2 rounds)",
    Round3: "HR Interview",
  },
  {
    NameOfCompany: "Acies Global",
    ProfileOffered: "Digital Analyst",
    Location: "Chennai",
    FunctionalArea: "B.Tech CSE",
    AnnualCTC: "INR. 3.75 LPA ",
    ForBatch: 2023,
    Round1: "Aptitude Test",
    Round2: "Coding Test",
    Round3: "HR Interview",
  },
  {
    NameOfCompany: "Birlasoft",
    ProfileOffered: "Trainee Engineer",
    Location: "Pan India",
    FunctionalArea: "B.Tech CSE, ECE",
    AnnualCTC: "INR. 3.60 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Aptitude Test",
    Round2: "Group Discussion",
    Round3: "Technical interview",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "My Real Data",
    ProfileOffered: "Advisor Technical Support",
    Location: "Gurgaon",
    FunctionalArea: "BCA, B.Tech All",
    AnnualCTC: "INR. 4.00 LPA - INR. 5.50 LPA",
    ForBatch: 0,
    Round1: "Aptitude Test",
    Round2: "Technical interview",
    Round3: "HR Interview",
  },
  {
    NameOfCompany: "Go Digit General Insurance",
    ProfileOffered: "Graduate Trainee Engineer",
    Location: "Bangalore, Pune, Bhubaneshwar or Trivandrum",
    FunctionalArea: "B.Tech CSE, ECE (AI/ML)",
    AnnualCTC: "INR. 4.50 LPA",
    ForBatch: 0,
    Round1: "Aptitude Test",
    Round2: "Coding Test",
    Round3: "HR Interview",
  },
  {
    NameOfCompany: "Remote State",
    ProfileOffered: "Software Developer",
    Location: "Noida",
    FunctionalArea: "BCA, B.Tech CSE, ECE",
    AnnualCTC: "INR. 5.00 LPA",
    ForBatch: 0,
    Round1: "Aptitude Test",
    Round2: "Technical interview",
    Round3: "HR Interview",
  },
  {
    NameOfCompany: "Einfochips",
    ProfileOffered: "Trainee Engineer",
    Location: "Ahmedabad / Pune / Noida / Bangalore",
    FunctionalArea: "B.Tech / M.Tech – CSE, IT, ECE",
    AnnualCTC: "INR. 4.00 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Aptitude Test",
    Round2: "Technical interview",
    Round3: "HR Interview",
  },
  {
    NameOfCompany: "Q1 Technologies ",
    ProfileOffered: "Recruitment Executive / Business Development",
    Location: "Noida",
    FunctionalArea: "B.Tech CSE, ECE, BCA, BBA, B.Com",
    AnnualCTC: "INR. 2.10 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Aptitude Test",
    Round2: "Technical interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Sarcon Technologies",
    ProfileOffered: "PHP Laravel Developer / Digital Marketing Executive",
    Location: "Bangalore",
    FunctionalArea: "B.Tech CSE, ECE, BCA, BAJMC",
    AnnualCTC: "INR. 3.00 LPA - INR. 6.00 LPA",
    ForBatch: 0,
    Round1: "Online test",
    Round2: "Technical interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Solulab Inc.",
    ProfileOffered: "NodeJS Developer",
    Location: "Ahmedabad",
    FunctionalArea: "B.Tech CSE",
    AnnualCTC: "INR. 3.36 LPA",
    ForBatch: 2023,
    Round1: "Written Test",
    Round2: "Technical interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Accolite Digital",
    ProfileOffered: "Software Development Engineer",
    Location: "Bangalore",
    FunctionalArea: "B.Tech / M.Tech CSE, IT, ECE (Only Female)",
    AnnualCTC: "INR. 8.00 LPA ",
    ForBatch: "2023 and 2024",
    Round1: "Online Round (Technical)",
    Round2: "Coding Round",
    Round3: "Technical Interview",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "Capillary Technologies",
    ProfileOffered: "Software Developer / Business Analyst",
    Location: "Bangalore",
    FunctionalArea: "B.Tech CSE, IT, ECE, Civil, BCA",
    AnnualCTC: "SD - INR. 12.00 LPA\n\nBA - INR. 6.00 LPA",
    ForBatch: 2023,
    Round1: "Online test",
    Round2: "Technical interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Wavelabs Technology ",
    ProfileOffered: "Video Specialist",
    Location: "Hyderabad",
    FunctionalArea: "BCA, BAJMC",
    AnnualCTC: "INR. 3.20 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Online Aptitude Test",
    Round2: "HR Interview",
    Round3: "Technical interview",
  },
  {
    NameOfCompany: "Hexaview Technologies Pvt Ltd",
    ProfileOffered: "Application Engineer / Technical Staff",
    Location: "Noida",
    FunctionalArea: "BCA, B.Tech / M.Tech CSE, ECE",
    AnnualCTC: "INR. 5.00 LPA - INR. 7.00 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Aptitude Test",
    Round2: "Coding Test",
    Round3: "Technical interview (Round 1-2)",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "Infogain Software",
    ProfileOffered: "Software Engineer Trainee ",
    Location: "Bangalore",
    FunctionalArea: "B.Tech / M.Tech CSE, ECE, MAE",
    AnnualCTC: "INR. 4.00 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Online (Aptitude + Technical)",
    Round2: "Coding Test",
    Round3: "Technical interview",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "L&T Technology Services",
    ProfileOffered: "Engineer Trainee",
    Location: "Mysore, Vadodara, Chennai , Mumbai, Bangalore",
    FunctionalArea: "B.Tech CSE, ECE",
    AnnualCTC: "INR. 4.00 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Written Exam",
    Round2: "Group Discussion",
    Round3: "Technical interview",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "The Math Company",
    ProfileOffered: "Analyst",
    Location: "Bangalore, Pune, Chennai",
    FunctionalArea: "B.Tech CSE, IT",
    AnnualCTC: "INR. 4.50 LPA",
    ForBatch: 2023,
    Round1: "Online Aptitude Test",
    Round2: "HR Interview",
    Round3: "Technical interview",
  },
  {
    NameOfCompany: "MU Sigma",
    ProfileOffered: "Trainee Decision Scientist",
    Location: "Bangalore",
    FunctionalArea: "B.Tech / M.Tech CSE, ECE, MAE",
    AnnualCTC: "INR. 3.50 LPA",
    ForBatch: 2023,
    Round1: "Group Discussion ",
    Round2: "Technical Interview",
    Round3: "HR Interview",
  },
  {
    NameOfCompany: "Lido Learning",
    ProfileOffered: "Business Development Executive",
    Location: "Pan India",
    FunctionalArea: "B.Tech All, BCA, MBA, BBA, B.Com, BAJMC",
    AnnualCTC: "INR. 5.50 LPA",
    ForBatch: 2023,
    Round1: "Online Aptitude Test",
    Round2: "HR Interview",
    Round3: "Technical interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Indian Hume Pipes",
    ProfileOffered: "Civil  Engineer- Site and Factory ",
    Location: "Pan India",
    FunctionalArea: "B.Tech Civil",
    AnnualCTC: "INR. 3.50 LPA",
    ForBatch: 2023,
    Round1: "Online Aptitude Test",
    Round2: "HR Interview",
    Round3: "Technical interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Board Infinity",
    ProfileOffered: "Career Guide",
    Location: "Noida, Mumbai",
    FunctionalArea: "B.Tech All, MBA, BBA, B.Com",
    AnnualCTC: "INR. 5.50 LPA - INR. 7.00 LPA",
    ForBatch: 2023,
    Round1: "Online test ",
    Round2: "Group discussion",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Bright Champs Technology",
    ProfileOffered: "Coding Educator",
    Location: "Bangalore (WFH)",
    FunctionalArea: "B.Tech CSE, BCA",
    AnnualCTC: "INR. 3.50 LPA - INR. 5.00 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Online Aptitude Test",
    Round2: "Coding Test",
    Round3: "Technical interview",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "WNS Global Services",
    ProfileOffered: "Data Analyst",
    Location: "Pan India",
    FunctionalArea: "B.Tech CSE, ECE, EEE",
    AnnualCTC: "INR. 4.00 LPA",
    ForBatch: 2023,
    Round1: "Online (Aptitude + Technical)",
    Round2: "Technical interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Hike Education",
    ProfileOffered: "Career Development Manager",
    Location: "Delhi/Gurgaon/Mumbai/Hyderabad/Jaipur",
    FunctionalArea: "B.Tech All, Biotech All, B.Pharma, BBA, B.Com",
    AnnualCTC: "INR. 4.80 LPA",
    ForBatch: 2023,
    Round1: "Group discussion",
    Round2: "HR Interview",
    Round3: '""',
    Round4: '""',
  },
  {
    NameOfCompany: "Jaro Education",
    ProfileOffered: "Career Development Executive",
    Location: "Pan India",
    FunctionalArea: "MBA, B.Tech All, BBA, B.Com, ALS, BAJMC",
    AnnualCTC: "UG: INR. 4.80 LPA\nPG: INR. 6.06 LPA - 7.46 LPA",
    ForBatch: 2023,
    Round1: "Group discussion",
    Round2: "HR Interview",
    Round3: "Behavioral Assessment",
    Round4: '""',
  },
  {
    NameOfCompany: "Nerdy Turtlez",
    ProfileOffered: "Subject Matter Expert, Operations",
    Location: "Kolkata",
    FunctionalArea: "Biotech, B.Pharma, BAJMC, B.Tech, BCA",
    AnnualCTC: "INR. 2.10 LPA - INR. 2.53 LPA",
    ForBatch: 2023,
    Round1: "Online test ",
    Round2: "Group discussion",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Wipro Limited",
    ProfileOffered: "Project Leader,  WLP Candidate",
    Location: "Pan India",
    FunctionalArea: "B.Tech CSE, ECE, BCA",
    AnnualCTC: "INR. 1.85 LPA - INR. 3.50 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Aptitude Test.",
    Round2: "Coding Round",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Digiversal Consultant Pvt Ltd",
    ProfileOffered:
      "Research Associate, Content Writer, Social Media, Client Relations",
    Location: "Noida, Indore, Hyderabad",
    FunctionalArea:
      "B.Tech All, Biotech, Psychology, B.Pharma, BAJMC, MAJMC, BBA, B.Com",
    AnnualCTC: "INR. 3.00 LPA",
    ForBatch: 0,
    Round1: "Online test ",
    Round2: "Group discussion",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Rightful Labs",
    ProfileOffered: "Digital Campaign Analyst / Marketing Intern",
    Location: "Bhopal",
    FunctionalArea: "BCA, BAJMC",
    AnnualCTC: "INR. 2.70 LPA - 3.00 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Online (Aptitude + Technical)",
    Round2: "Technical interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "MTX IT Consulting Services Pvt Ltd",
    ProfileOffered: "Consultant Trainee",
    Location: "Hyderabad",
    FunctionalArea: "B.Tech CSE",
    AnnualCTC: "INR. 10.40",
    ForBatch: "2022 & 2023",
    Round1: "Aptitude Test",
    Round2: "Technical interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Make my Trip",
    ProfileOffered: "Quality Assurance Engineer",
    Location: "Pan India",
    FunctionalArea: "B.Tech CSE",
    AnnualCTC: "INR. 7.50 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Online (Aptitude + Technical)",
    Round2: "Technical interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "NTT Data",
    ProfileOffered: "Software Trainee ",
    Location: "Bangalore",
    FunctionalArea: "B.Tech CSE",
    AnnualCTC: "INR. 5.00 LPA",
    ForBatch: "2022 & 2023",
    Round1: "Online Test",
    Round2: "Coding Test",
    Round3: "Technical interview",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "Aliens Group",
    ProfileOffered: "Business Development Associate",
    Location: "Hyderabad",
    FunctionalArea: "No Criteria",
    AnnualCTC: "6.0 LPA",
    ForBatch: 2023,
    Round1: "Online interview",
    Round2: "personality assessment",
    Round3: "video presentation",
    Round4: '""',
  },
  {
    NameOfCompany: "Yespeal tecchnologies",
    ProfileOffered: "Software Developer",
    Location: "Bangalore",
    FunctionalArea: "B.Tech CSE, ECE, MCA, BCA",
    AnnualCTC: "4.00 LPA - INR. 9.50 LPA ",
    ForBatch: 2023,
    Round1: " Aptitude Test (General)  ",
    Round2: "\nGroup Discussion",
    Round3: "Technical Test on C, C++ Python & Java",
    Round4: "Technical & Personal HR round",
  },
  {
    NameOfCompany: "Hexaware technologies",
    ProfileOffered: "PGET (Premier Graduate Engineer Trainee)",
    Location: "Chennai, Pune or Mumbai",
    FunctionalArea: "B.Tech  CSE/IT/ECE/EEE/ETC/EIE/ICE",
    AnnualCTC: "6.0 LPA",
    ForBatch: 2023,
    Round1: "Written Test( Aptitude Test+ Tech- Domain Test)",
    Round2: "Communication Test",
    Round3: "Interview (Technical+ HR)",
    Round4: '""',
  },
  {
    NameOfCompany: "My Captain",
    ProfileOffered: "Operations Executive ",
    Location: "Bangalore",
    FunctionalArea: " B.Tech All, MCA, BCA ",
    AnnualCTC: "5.0 LPA",
    ForBatch: 2023,
    Round1: " CV Screening ",
    Round2: "Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "To The New",
    ProfileOffered: "Software Engineer Trainee / Quality Engineer Trainee ",
    Location: "Noida",
    FunctionalArea: "B.Tech CSE, MCA",
    AnnualCTC: "4.5 LPA",
    ForBatch: 2023,
    Round1: "Aptitude Test",
    Round2: "Coding test",
    Round3: "Technical Interview",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "Artech Infosystem",
    ProfileOffered: "Associate Recruiter",
    Location: "Bhopal",
    FunctionalArea: "B.Tech -  All, Streams, MCA, BCA, ",
    AnnualCTC: "4.68 LPA ",
    ForBatch: 2023,
    Round1: "Aptitude Test",
    Round2: "Group discussion",
    Round3: "Mangerial Interview + Technical",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "Schaeffler Technology Solution",
    ProfileOffered: "Graduate Engineer Trainee ",
    Location: "Pune",
    FunctionalArea: "B.Tech ECE, CSE ",
    AnnualCTC: "6.00 LPA  ",
    ForBatch: 2023,
    Round1: "Online test",
    Round2: "Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "U-Certify",
    ProfileOffered: "Web Application Developer",
    Location: "Noida",
    FunctionalArea: "B.Tech - All, BCA, MCA",
    AnnualCTC: "4.20 LPA",
    ForBatch: 2023,
    Round1: "Online Assessment",
    Round2: "Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Podar Education Group",
    ProfileOffered: "STEM Innovation Labs  ",
    Location: "Maharashtra, Gujarat, Karnataka, MP. Bihar",
    FunctionalArea: "BE/BTech students from Robotics, Programming, Python",
    AnnualCTC: "3.0 LPA to 4.0 LPA",
    ForBatch: 2023,
    Round1: "Technical Interview",
    Round2: "HR Interview",
    Round3: '""',
    Round4: '""',
  },
  {
    NameOfCompany: "JIO-FYND",
    ProfileOffered: "Graduate Software Engineer",
    Location: '""',
    FunctionalArea: "B.Tech (All Streams), BCA, B.Sc IT & MCA",
    AnnualCTC: "13.5 LPA ",
    ForBatch: 2023,
    Round1: "Online test",
    Round2: "Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Mercer | Mettl",
    Location: '""',
    FunctionalArea: '""',
    AnnualCTC: '""',
    ForBatch: 2023,
    Round1: "Online test (Technical + Aptitude)",
    Round2: "Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Precisely",
    ProfileOffered:
      "Associate Support Engineer \n/ Trainee software engineer\n",
    Location: '""',
    FunctionalArea: "B.Tech (CS/IT)",
    AnnualCTC: "8.5 LPA",
    ForBatch: 2023,
    Round1: "Online Aptitude Test",
    Round2: "Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Netcracker Technology",
    ProfileOffered: "Software Engineer",
    Location: '""',
    FunctionalArea: "o B.Tech (CS / IT /EC / ET / EEE)",
    AnnualCTC: "8.0 LPA",
    ForBatch: 2023,
    Round1: "Aptitude test",
    Round2: "Coding test",
    Round3: "Technical Interview",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "Ericsson India Global Services Pvt. Ltd.",
    ProfileOffered: "Assistant Engineer Trainee ",
    Location:
      "Gurgaon / Chennai / Noida / Bangalore / Kolkata / Other Locations (EGI Office PAN India) ",
    FunctionalArea: "B.Tech CSE, ECE",
    AnnualCTC: "3.75 LPA",
    ForBatch: 2023,
    Round1: "Online  Test",
    Round2: "Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "JSW",
    ProfileOffered: "Graduate Engineer Trainee ",
    Location: "Pan India",
    FunctionalArea: "B.Tech -  Civil, Biotech, ME, CSE, ECE ",
    AnnualCTC: "8.5 LPA",
    ForBatch: 2023,
    Round1: "Common Test (Online Aptitude & Domain Knowledge) ",
    Round2: "Group discussion",
    Round3: "Personal Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Evive Software Analytics Pvt Ltd.",
    ProfileOffered: "Software Developer - Backend/Frontend/BI ",
    Location: "Banglore",
    FunctionalArea: "B.Tech - CSE, ECE",
    AnnualCTC: "8.0 LPA",
    ForBatch: 2023,
    Round1: "Online Technical and Aptitude",
    Round2: " Tech Interview-1: Coding & Basic Concepts ",
    Round3: " Tech Interview-2: Technical and Fitment ",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "Koeing Solutions Pvt Ltd.",
    ProfileOffered: "Dot Net Developer / Corporate Trainer  ",
    Location: "Work From Home (Permanent)   ",
    FunctionalArea: "B.Tech CSE, ECE,  MCA & BCA",
    AnnualCTC: "6.0 - 8.0 LPA",
    ForBatch: 2023,
    Round1: "Online  Test",
    Round2: "Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Round The Clock Technologies",
    ProfileOffered: "Software Engineer",
    Location: "Noida",
    FunctionalArea: "B.Tech CSE, MCA",
    AnnualCTC: "3.60 LPA ",
    ForBatch: 2023,
    Round1: "Online objective test",
    Round2: "coding test",
    Round3: "Technical Interview",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "Applicate AI IT Solutions Pvt Ltd.",
    ProfileOffered:
      "Software Engineer - Full Stack  /  Software Test Engineer  /  Business Analyst Trainee",
    Location: "Gurgaon  ",
    FunctionalArea: "B.Tech All Streams, MCA, BCA, B.Sc IT",
    AnnualCTC: "6.0 LPA",
    ForBatch: 2023,
    Round1: "Aptitude test",
    Round2: "Coding test",
    Round3: "Technical Interview",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "Hewlett Packard",
    ProfileOffered: "CTG - COE",
    Location: '""',
    FunctionalArea: "B.Tech (CS / IT /EC / ET / EEE)",
    AnnualCTC: "8.5 LPA",
    ForBatch: 2023,
    Round1: "Written Round",
    Round2: "Technical Round-1, round-2 and round-3",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: " Netsmartz IT Solutions",
    ProfileOffered: "Junior Software Engineer  / Junior Technical Consultant",
    Location: "  Noida / Gurgaon ",
    FunctionalArea: " B.Tech - CSE, ECE, MCA",
    AnnualCTC: "3.6 LPA",
    ForBatch: 2023,
    Round1: "Online Coding test",
    Round2: "Technical interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Amazon",
    ProfileOffered: "Software Development Engineer 1 ",
    Location: '""',
    FunctionalArea: "B.Tech CSE, ECE, MCA, BCA",
    AnnualCTC: "17 to 26 to 41 LPA",
    ForBatch: 2023,
    Round1: "Online test",
    Round2: "Technical interview (Multiple rounds)",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Tekion",
    ProfileOffered: "Associate Software Engineer",
    Location: "Chennai",
    FunctionalArea: " B.Tech - CSE, ECE, MCA",
    AnnualCTC: "5.0 to 6.0 LPA",
    ForBatch: 2023,
    Round1: "Online  Test",
    Round2: "Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "UI-Paths",
    ProfileOffered: "RPA Developer",
    Location: '""',
    FunctionalArea: " B.Tech - CSE, ECE, MCA",
    AnnualCTC: "9.0 LPA",
    ForBatch: 2023,
    Round1: "Written Exam",
    Round2: "Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Renault Nissan Technology and Business Centre",
    ProfileOffered: "Graduate Engineering Trainee",
    Location: "Chennai",
    FunctionalArea: "B.Tech All Streams",
    AnnualCTC: "4.25 LPA",
    ForBatch: 2023,
    Round1: "Online  Test",
    Round2: "Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Celebal Technologies",
    ProfileOffered: "Junior Associate",
    Location: "Jaipur, Pune, Noida, Jalpaiguri, Ajmer ",
    FunctionalArea: "B.Tech/M.Tech - CSE, IT, ECE, MCA, BCA",
    AnnualCTC: "6.5 to 8.5 LPA",
    ForBatch: 2023,
    Round1: "Online test (Quantative + verbal + technical)",
    Round2: "Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Demand Farm (SAAS Product Company)",
    ProfileOffered: "Product Engineer",
    Location: "Pune",
    FunctionalArea: "B.Tech - CSE, ECE, MCA, BCA",
    AnnualCTC: "7.0 to 8.0 LPA",
    ForBatch: 2023,
    Round1: "Written Exam",
    Round2: "Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Sopra Steria India",
    ProfileOffered: "Engineer Trainee",
    Location: "Noida, Chennai & Bangalore ",
    FunctionalArea: " B.Tech - CSE,IT,  ECE, MCA",
    AnnualCTC: "6.0 LPA",
    ForBatch: 2023,
    Round1: "Online Technical and Aptitude",
    Round2: "Technical Interview",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Trane Technologies",
    ProfileOffered: "Graduate Engineer Trainee ",
    Location: "Bangalore/Chennai  ",
    FunctionalArea: " B.Tech - CSE, IT, ECE, Mechanical  \n",
    AnnualCTC: "6.0 LPA",
    ForBatch: 2023,
    Round1: "Aptitude test",
    Round2: "Technical round",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "Amadeus Labs Bangalore",
    ProfileOffered: "Software Engineer",
    Location: "Banglore",
    FunctionalArea: "B.Tech CSE, ECE",
    AnnualCTC: "11.7 LPA",
    ForBatch: 2023,
    Round1: "Online Assessment-1 Technical and Coding",
    Round2: "Online Assessment 2  - SHL Aptitude Test",
    Round3: "Technical Interview",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "Genpact",
    ProfileOffered: "Technical Consultant",
    Location: '""',
    FunctionalArea: "B.Tech (All Branches) & MCA",
    AnnualCTC: "7.0 LPA",
    ForBatch: 2023,
    Round1: "Online Test-",
    Round2: "Group discussion",
    Round3: "Technical Interview",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "ZS ASSOCIATES",
    ProfileOffered: "Software (Test Engineer)",
    Location: '""',
    FunctionalArea: "B.Tech - (CS / IT)",
    AnnualCTC: "12.55 LPA",
    ForBatch: 2023,
    Round1: "Online Written Test",
    Round2: "Case study based round (PDSS)",
    Round3: "Technical interview",
    Round4: "HR Interview",
  },
  {
    NameOfCompany: "PaloAlto",
    ProfileOffered:
      "IT Software Developer\nSoftware Engineer - Network Services\n",
    Location: "Hyderabad / Banglore",
    FunctionalArea: "B.Tech - (CS / IT)",
    AnnualCTC: "56 LPA",
    ForBatch: 2023,
    Round1: "online assessment ",
    Round2: "Technical interview (Multiple rounds 2-3)",
    Round3: "HR Interview",
    Round4: '""',
  },
  {
    NameOfCompany: "ARGUSOFT",
    ProfileOffered: "Programmer Analyst",
    Location: "Pan India",
    FunctionalArea: "B.Tech - (CS / IT)",
    AnnualCTC: "7.12 LPA",
    ForBatch: 2023,
    Round1: " Online Aptitude Technical /Communication Skill Test ",
    Round2: "Personal Interview ( 1-3 rounds) ",
    Round3: "",
    Round4: "",
  },
  {
    NameOfCompany: "Network 18",
    ProfileOffered: "Software Engineer / DevOps Engineer",
    Location: "Delhi NCR",
    FunctionalArea: "B.Tech - CSE, ECE, MCA, BCA, B.Sc (IT)",
    AnnualCTC: "5.0 LPA",
    ForBatch: 2023,
    Round1: "Online test",
    Round2: "Technical round",
    Round3: "HR Interview",
    Round4: "",
  },
];

const companiesDataSlice = createSlice({
  name: "companiesData",
  initialState: { companies },
  reducers: {},
});
export const companiesDataActions = companiesDataSlice.actions;
export default companiesDataSlice;
