name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Use Node.js version >= 18

      - run: npm install
      - run: npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AMIPLACE_3C576 }} # Your Firebase service account secret
          projectId: amiplace-3c576
          channelId: live
          apiKey: ${{ secrets.VITE_FIREBASE_API_KEY }}                # Use secret for Firebase API key
          authDomain: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}        # Use secret for Auth domain
          storageBucket: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}  # Use secret for Storage bucket
          messagingSenderId: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }} # Use secret for Messaging sender ID
          appId: ${{ secrets.VITE_FIREBASE_APP_ID }}                  # Use secret for App ID
          measurementId: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}  # Use secret for Measurement ID
